apiVersion: v1
kind: Service
metadata:
  name: kube-token-server
spec:
  selector:
    app: kube-token-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
